# Generated by Django 3.2.9 on 2021-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='display_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
