# Generated by Django 3.2.9 on 2021-11-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolist_display_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='display_name1',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='display_name2',
        ),
    ]
